apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testnetes
  template:
    metadata:
      labels:
        app: testnetes
    spec:
      containers:
      - name: web
        image: celestialaghori/testnetes:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-url
        - name: FLASK_ENV
          value: "production"

