apiVersion: v1
kind: Service
metadata:
  name: testnetes-service
spec:
  type: LoadBalancer
  selector:
    app: testnetes
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 5000  # Must match containerPort

